# .github/release.yml

name: Release on npm
on:
  push:
    branches:
      - main
    paths:
      - "packages/zod/package.json"
      - "packages/zod/src/**"
      - ".github/workflows/release.yml"

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
      - run: pnpm run --filter @zod/resolution test:all
      - run: pnpm run prepublishOnly
        working-directory: ./packages/zod
     
      - name: Configure changelog
        if: ${{ steps.publish.outputs.type }}
        run: |
          echo '{"categories": [], "template": "## Commits:\n\n${{ '${{UNCATEGORIZED}}' }}", "pr_template": ${{ '"- ${{MERGE_SHA}} ${{TITLE}}"' }} }' > changelog_config.json
          cat changelog_config.json
          echo "last_tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
          echo "curr_commit=$(git rev-parse HEAD)" >> $GITHUB_ENV
